const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname,'..');
const base = process.env.FINANCE_TEST_URL || 'http://127.0.0.1:8133';
const php = code => execFileSync('php',['-r',code],{cwd:root,encoding:'utf8'}).trim();
const sid = php("chdir('public'); require '../app/init.php'; $d=new Database; $d->query('SELECT id,name,email FROM accounts LIMIT 1'); session_id(bin2hex(random_bytes(24))); session_start(); $_SESSION['auth_user']=$d->single(); echo session_id(); session_write_close();");
(async()=>{
  let browser;
  try {
    browser=await chromium.launch({headless:true});
    const context=await browser.newContext({viewport:{width:1600,height:1000}});
    await context.addCookies([{name:'PHPSESSID',value:sid,url:base}]);
    const page=await context.newPage(), errors=[]; page.on('pageerror',e=>errors.push(e.message));
    let saves=0,conflict=false,syncs=0;
    await page.route('**/procFinance/save',route=>{saves++; return route.fulfill(conflict ? {status:409,json:{status:'error',message:'HPP sudah diubah anggota tim. Muat ulang daftar.'}} : {json:{status:'success',version:1}});});
    await page.route('**/procFinance/sync',route=>{syncs++;return route.fulfill({json:{status:'success',message:'Pembaruan masuk antrean.',queued:1}});});
    const loaded=()=>page.waitForFunction(()=>document.querySelectorAll('.finance-store').length>0);
    await page.goto(base+'/panel/finance?shops=1&start=2026-09-01&end=2026-09-02'); await loaded();
    assert.equal(await page.locator('.finance-store').count(),1);
    assert.match(await page.locator('#finance-pending').innerText(),/Rp/);
    assert.match(await page.locator('#finance-released-quality').innerText(),/Data toko tersedia/);
    assert.equal(await page.locator('#finance-released-quality .is-partial').count(),0);
    const api=await context.request.get(base+'/procFinance/summary?shops=1&start=2026-09-01&end=2026-09-02');
    assert.equal(api.status(),200); assert.equal((await api.json()).stores.length,1);
    await page.locator('#finance-shops-trigger').click();
    await page.locator('[data-shop-value="2"]').click();
    await page.keyboard.press('Escape');
    await page.locator('#finance-filters button[type=submit]').click(); await loaded();
    assert.equal(await page.locator('.finance-store').count(),2);
    assert.equal(await page.inputValue('#finance-start'),'2026-09-01');
    assert.match(page.url(),/shops=1%2C2/);
    await page.reload(); await loaded(); assert.equal(await page.locator('#finance-shops option:checked').count(),2);
    await page.locator('#finance-shops-trigger').focus(); await page.keyboard.press('ArrowDown');
    const menu=page.locator('#finance-shops-options'); await menu.waitFor({state:'visible'});
    await page.keyboard.press('Enter'); assert.equal(await page.locator('#finance-shops option:checked').count(),3);
    await page.keyboard.press('Escape'); assert.equal(await page.locator('#finance-shops-trigger').getAttribute('aria-expanded'),'false');
    await page.locator('#finance-filters button[type=submit]').click(); await loaded();
    const output=path.join(root,'tmp/finance-ui'); fs.mkdirSync(output,{recursive:true});
    for(const width of [320,500,999,1600]) {
      await page.setViewportSize({width,height:1000});
      for(const theme of ['light','dark']) {
        await page.evaluate(t=>window.shopdashTheme.setMode(t),theme);
        assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow: '+width);
        await page.locator('#finance-shops-trigger').click(); await menu.waitFor({state:'visible'});
        const trigger=await page.locator('#finance-shops-trigger').boundingBox(),box=await menu.boundingBox();
        assert.ok(box.y>=trigger.y+trigger.height-1 && box.x>=0 && box.x+box.width<=width+1,'Dropdown below and in viewport');
        assert.ok(await menu.evaluate(el=>el.scrollWidth<=el.clientWidth),'Vertical scrolling only');
        const x=await menu.locator('li').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().x)); assert.ok(x.every(v=>Math.abs(v-x[0])<1));
        await menu.locator('button').last().focus(); await page.keyboard.press('Escape');
        assert.equal(await menu.isVisible(),false,JSON.stringify(await menu.evaluate(el=>({hidden:el.hidden,display:getComputedStyle(el).display,active:document.activeElement.id,expanded:document.getElementById('finance-shops-trigger').getAttribute('aria-expanded')}))));
        await page.evaluate(()=>scrollTo(0,0)); await page.screenshot({path:path.join(output,`${width}-${theme}.png`),animations:'disabled'});
      }
    }
    await page.locator('[data-finance-tab=details]').click(); await page.locator('.finance-table tbody tr').first().waitFor();
    assert.match(await page.locator('#finance-detail-scope').innerText(),/tanpa filter tanggal/);
    await page.selectOption('#finance-category','2'); await page.waitForFunction(()=>document.querySelector('#finance-detail-pagination').textContent.includes('baris'));
    assert.match(await page.locator('#finance-detail-scope').innerText(),/tanggal dana dilepas/);
    await page.locator('#finance-order-search').fill('NONEXISTENT-TEST'); await page.locator('#finance-order-search-form button').click();
    await page.locator('.finance-empty').waitFor();
    await page.locator('[data-finance-tab=cost]').click(); await page.locator('[data-edit-cost]').first().waitFor();
    await page.locator('[data-edit-cost]').first().click(); await page.locator('#finance-cost-dialog').waitFor({state:'visible'});
    await page.locator('#finance-cost-value').fill('20000'); await page.locator('#finance-cost-date').fill('2026-09-01');
    await page.locator('#finance-preview-cost').click(); await page.locator('#finance-cost-preview').waitFor({state:'visible'});
    assert.match(await page.locator('#finance-cost-preview').innerText(),/pesanan tersimpan/);
    await page.locator('#finance-cost-value').fill('21000'); assert.equal(await page.locator('#finance-save-cost').isDisabled(),true);
    await page.locator('#finance-preview-cost').click(); await page.locator('#finance-cost-preview').waitFor({state:'visible'});
    conflict=true; await page.locator('#finance-save-cost').click(); await page.locator('#finance-cost-error').waitFor({state:'visible'});
    assert.equal(await page.inputValue('#finance-cost-value'),'21000'); assert.equal(await page.locator('#finance-save-cost').isDisabled(),true);
    conflict=false; await page.locator('#finance-preview-cost').click(); await page.locator('#finance-cost-preview').waitFor({state:'visible'});
    await page.locator('#finance-save-cost').click(); await page.locator('#finance-cost-dialog').waitFor({state:'hidden'}); assert.equal(saves,2);
    await page.locator('[data-edit-cost]').first().waitFor(); await page.locator('[data-edit-cost]').first().click();
    await page.setViewportSize({width:320,height:720});
    assert.ok(await page.locator('#finance-cost-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));
    await page.screenshot({path:path.join(output,'hpp-mobile.png')}); await page.keyboard.press('Escape');
    assert.equal(await page.locator('#finance-cost-dialog').isVisible(),false);
    const csrf=await page.locator('#finance-page').getAttribute('data-csrf');
    assert.equal((await context.request.post(base+'/procFinance/save',{data:{}})).status(),403);
    const catalog=await (await context.request.get(base+'/procFinance/catalog?shops=1')).json();
    const item=catalog.rows[0];
    const unconfirmed={shop_id:item.shop_id,product_id:item.product_id,model_id:item.model_id,version:item.version,unit_cost:'20000',valid_from:'2026-09-01',expires:Math.floor(Date.now()/1000)+600,token:'0'.repeat(64)};
    assert.equal((await context.request.post(base+'/procFinance/save',{headers:{'X-CSRF-Token':csrf},data:unconfirmed})).status(),409);
    assert.equal((await context.request.post(base+'/procFinance/preview',{headers:{'X-CSRF-Token':csrf},data:{shop_id:999,product_id:'1',model_id:'0',version:0,unit_cost:'-1',valid_from:'2026-09-01'}})).status(),422);
    assert.equal((await context.request.get(base+'/procFinance/summary?shops=999')).status(),422);
    await page.route('**/procFinance/summary?*',route=>route.fulfill({status:500,json:{status:'error',message:'Koneksi uji gagal. Coba lagi.'}}));
    await page.locator('#finance-filters button[type=submit]').click(); await page.locator('#finance-error').waitFor({state:'visible'});
    assert.equal(await page.locator('#finance-pending').innerText(),'Belum dapat dimuat');
    await page.unroute('**/procFinance/summary?*'); await page.locator('#finance-retry').click(); await loaded();
    await page.locator('#finance-sync').click(); await page.waitForFunction(()=>!document.querySelector('#finance-sync').disabled); assert.equal(syncs,1);
    assert.deepEqual(errors,[]);
    console.log('PASS: live reads, multi-shop filters, dates, details, HPP preview, mocked saves/conflict, CSRF, failure recovery, responsive themes, dropdown and keyboard');
  } finally { await browser?.close(); php("session_id('"+sid+"');session_start();$_SESSION=[];session_destroy();"); }
})().catch(e=>{console.error(e);process.exitCode=1;});
