CREATE TABLE IF NOT EXISTS ad_performance_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shop_id INT NOT NULL,
  period_start DATETIME NOT NULL,
  period_end DATETIME NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Jakarta',
  campaign_type VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ok',
  impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
  clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ctr DECIMAL(12,4) NOT NULL DEFAULT 0,
  orders BIGINT UNSIGNED NOT NULL DEFAULT 0,
  items_sold BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sales DECIMAL(20,2) NOT NULL DEFAULT 0,
  ad_cost DECIMAL(20,2) NOT NULL DEFAULT 0,
  roas DECIMAL(12,4) NULL,
  broad_sales DECIMAL(20,2) NOT NULL DEFAULT 0,
  broad_orders BIGINT UNSIGNED NOT NULL DEFAULT 0,
  broad_items_sold BIGINT UNSIGNED NOT NULL DEFAULT 0,
  broad_roas DECIMAL(12,4) NULL,
  raw_payload LONGTEXT NULL,
  fetched_at DATETIME NOT NULL,
  error_message TEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY ad_performance_window (shop_id, period_start, period_end, campaign_type),
  KEY ad_performance_shop_period (shop_id, period_start),
  KEY ad_performance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
