ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS sync_status VARCHAR(24) NULL,
  ADD COLUMN IF NOT EXISTS sync_attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sync_next_retry_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS sync_last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS detail_synced_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS package_synced_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS income_synced_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS sync_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shop_id INT NOT NULL,
  channel_id SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  sync_type VARCHAR(50) NOT NULL DEFAULT 'orders',
  idempotency_key VARCHAR(190) NOT NULL,
  sync_run_id BIGINT UNSIGNED NULL,
  mode VARCHAR(16) NOT NULL DEFAULT 'diff',
  status VARCHAR(16) NOT NULL DEFAULT 'queued',
  page_sentinel TEXT NULL,
  page_number INT NOT NULL DEFAULT 1,
  total_indexed INT NOT NULL DEFAULT 0,
  total_detail INT NOT NULL DEFAULT 0,
  processed_detail INT NOT NULL DEFAULT 0,
  failed_detail INT NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  lease_until DATETIME NULL,
  last_error TEXT NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY sync_jobs_idempotency (shop_id, sync_type, idempotency_key), KEY sync_jobs_shop_status (shop_id, status), KEY sync_jobs_retry (status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sync_job_id BIGINT UNSIGNED NOT NULL,
  shop_id INT NOT NULL,
  channel_id SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  sync_type VARCHAR(50) NOT NULL DEFAULT 'orders',
  job_id BIGINT UNSIGNED NOT NULL,
  phase VARCHAR(24) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'running',
  fetched_pages INT NOT NULL DEFAULT 0,
  indexed_orders INT NOT NULL DEFAULT 0,
  detail_success INT NOT NULL DEFAULT 0,
  detail_failed INT NOT NULL DEFAULT 0,
  api_requests INT NOT NULL DEFAULT 0,
  heartbeat_at DATETIME NULL,
  last_error TEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  PRIMARY KEY (id), KEY sync_runs_job (job_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_pages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sync_run_id BIGINT UNSIGNED NOT NULL,
  job_id BIGINT UNSIGNED NOT NULL,
  page_number INT NOT NULL,
  sentinel TEXT NULL,
  next_sentinel TEXT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'queued',
  attempts INT NOT NULL DEFAULT 0,
  orders_indexed INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  lease_until DATETIME NULL,
  last_error TEXT NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  PRIMARY KEY (id), UNIQUE KEY sync_pages_job_page (job_id, page_number), KEY sync_pages_claim (status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_job_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'queued',
  attempts INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  lease_until DATETIME NULL,
  last_error TEXT NULL,
  completed_at DATETIME NULL,
  PRIMARY KEY (id), UNIQUE KEY sync_job_orders_unique (job_id, order_id), KEY sync_job_orders_claim (job_id, status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE sync_jobs
  ADD COLUMN IF NOT EXISTS channel_id SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS sync_type VARCHAR(50) NOT NULL DEFAULT 'orders',
  ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(190) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sync_run_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS mode VARCHAR(16) NOT NULL DEFAULT 'diff',
  ADD COLUMN IF NOT EXISTS page_sentinel TEXT NULL,
  ADD COLUMN IF NOT EXISTS page_number INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS total_indexed INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_detail INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS processed_detail INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failed_detail INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lease_until DATETIME NULL,
  ADD COLUMN IF NOT EXISTS last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS completed_at DATETIME NULL;

ALTER TABLE sync_runs
  ADD COLUMN IF NOT EXISTS sync_job_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS shop_id INT NULL,
  ADD COLUMN IF NOT EXISTS channel_id SMALLINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS sync_type VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS job_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS phase VARCHAR(24) NULL,
  ADD COLUMN IF NOT EXISTS fetched_pages INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS indexed_orders INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS detail_success INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS detail_failed INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_requests INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS heartbeat_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS completed_at DATETIME NULL;

ALTER TABLE sync_pages
  ADD COLUMN IF NOT EXISTS sync_run_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS job_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS sentinel TEXT NULL,
  ADD COLUMN IF NOT EXISTS next_sentinel TEXT NULL,
  ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS orders_indexed INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS next_retry_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS lease_until DATETIME NULL,
  ADD COLUMN IF NOT EXISTS last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS completed_at DATETIME NULL;
