CREATE TABLE IF NOT EXISTS chat_shop_snapshots (
  shop_id INT NOT NULL,
  remote_shop_id BIGINT NULL,
  remote_user_id BIGINT NULL,
  remote_shop_name VARCHAR(255) NULL,
  remote_country VARCHAR(8) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  unread_count INT NOT NULL DEFAULT 0,
  conversation_count INT NOT NULL DEFAULT 0,
  last_message_id VARCHAR(80) NULL,
  last_message_region VARCHAR(8) NULL,
  next_timestamp_nano VARCHAR(80) NULL,
  session_expires_at DATETIME NULL,
  last_sync_at DATETIME NULL,
  error_message TEXT NULL,
  payload LONGTEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (shop_id),
  KEY chat_snapshots_status (status),
  KEY chat_snapshots_sync (last_sync_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chat_conversations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shop_id INT NOT NULL,
  remote_conversation_id VARCHAR(80) NOT NULL,
  buyer_id BIGINT NULL,
  buyer_name VARCHAR(255) NULL,
  buyer_avatar VARCHAR(500) NULL,
  buyer_shop_id BIGINT NULL,
  status VARCHAR(32) NULL,
  is_blocked TINYINT(1) NOT NULL DEFAULT 0,
  unread_count INT NOT NULL DEFAULT 0,
  latest_message_id VARCHAR(80) NULL,
  latest_message_type VARCHAR(32) NULL,
  latest_message_source VARCHAR(64) NULL,
  latest_message_text TEXT NULL,
  latest_message_at DATETIME NULL,
  latest_message_region VARCHAR(8) NULL,
  raw_payload LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY chat_conversations_remote (shop_id, remote_conversation_id),
  KEY chat_conversations_list (shop_id, latest_message_at),
  KEY chat_conversations_unread (shop_id, unread_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shop_id INT NOT NULL,
  remote_conversation_id VARCHAR(80) NOT NULL,
  remote_message_id VARCHAR(80) NOT NULL,
  sender_id BIGINT NULL,
  receiver_id BIGINT NULL,
  sender_name VARCHAR(255) NULL,
  message_type VARCHAR(32) NULL,
  direction VARCHAR(16) NULL,
  content_text TEXT NULL,
  content_json LONGTEXT NULL,
  remote_created_at DATETIME NULL,
  remote_status VARCHAR(32) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY chat_messages_remote (shop_id, remote_message_id),
  KEY chat_messages_conversation (shop_id, remote_conversation_id, remote_created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
