<?php
$movement = $data['movement'] ?? ['rows' => [], 'summary' => [], 'days' => 0];
$activeShop = (int)($data['active_shop_id'] ?? 0);
$activeFilter = (string)($data['movement_filter'] ?? '');
$rows = $movement['rows'] ?? [];
$filterLabels = ['fast' => 'Fast moving', 'slow' => 'Slow moving', 'dead' => 'Dead stock', 'empty' => 'Stok habis'];
$filterUrl = static function (string $filter) use ($activeShop): string {
  $query = ['shop_id' => $activeShop, 'view' => 'movement'];
  if ($filter !== '') $query['movement'] = $filter;
  return burl . '/panel/products?' . htmlspecialchars(http_build_query($query), ENT_QUOTES, 'UTF-8');
};
if ($activeFilter !== '' && isset($filterLabels[$activeFilter])) {
  $rows = array_values(array_filter($rows, static fn(array $row): bool => ($row['movement_key'] ?? '') === $activeFilter));
}
?>
<section id="product-movement-page" aria-labelledby="product-movement-title">
  <div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 id="product-movement-title" class="text-2xl font-bold">Pergerakan produk</h1><p class="mt-1 text-sm text-base-content/70">Laju penjualan dan posisi stok untuk <?= (int)($movement['days'] ?? 0); ?> hari terakhir.</p></div><div class="movement-toolbar"><a class="btn btn-ghost" href="<?= burl; ?>/panel/products?shop_id=<?= $activeShop; ?>">Daftar produk</a><div class="movement-shop"><label for="selectedShopDisplay">Toko</label><?php require __DIR__ . "/templates/shop-picker.php"; ?></div></div></div>
  <div class="movement-filters" aria-label="Filter pergerakan produk">
    <?php foreach ([['fast','Fast moving','trending_up'],['slow','Slow moving','hourglass_top'],['dead','Dead stock','inventory_2'],['empty','Stok habis','remove_shopping_cart']] as [$key,$label,$icon]): $isActive = $activeFilter === $key; ?><a class="rounded-xl border <?= $isActive ? 'border-primary bg-primary/10' : 'border-base-300 bg-base-100'; ?> p-3 transition hover:border-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary" href="<?= $filterUrl($key); ?>" aria-label="Tampilkan <?= (int)($movement['summary'][$key] ?? 0); ?> produk <?= htmlspecialchars($label, ENT_QUOTES); ?>" aria-current="<?= $isActive ? 'page' : 'false'; ?>"><span class="material-symbols-outlined text-base-content/70" aria-hidden="true"><?= $icon; ?></span><strong class="mt-2 block text-xl"><?= (int)($movement['summary'][$key] ?? 0); ?></strong><span class="text-xs text-base-content/70"><?= $label; ?></span></a><?php endforeach; ?><a class="rounded-xl border <?= $activeFilter === '' ? 'border-primary bg-primary/10' : 'border-base-300 bg-base-100'; ?> p-3 transition hover:border-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary" href="<?= $filterUrl(''); ?>" aria-label="Tampilkan semua produk" aria-current="<?= $activeFilter === '' ? 'page' : 'false'; ?>"><span class="material-symbols-outlined text-base-content/70" aria-hidden="true">list</span><strong class="mt-2 block text-xl">Semua</strong><span class="text-xs text-base-content/70">Tampilkan semua</span></a>
  </div>
  <?php if ($activeFilter !== '' && isset($filterLabels[$activeFilter])): ?><div class="mb-5 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-primary/30 bg-primary/5 px-3 py-2 text-sm"><span>Filter aktif: <strong><?= htmlspecialchars($filterLabels[$activeFilter], ENT_QUOTES); ?></strong></span><a class="btn btn-ghost btn-xs" href="<?= $filterUrl(''); ?>">Tampilkan semua</a></div><?php endif; ?>
  <details class="movement-guide"><summary>Cara membaca pergerakan produk</summary><p class="text-sm"> Fast moving memakai laju jual tinggi dibanding produk lain di toko. Slow moving masih terjual dengan laju lebih rendah. Dead stock memiliki stok tetapi tidak terjual selama periode ini. Stok habis dipisahkan dari dead stock.</p></details>
  <div class="overflow-hidden rounded-xl border border-base-300 bg-base-100"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-base-300 p-4"><div><h2 class="font-bold">Rekap penjualan dan stok</h2><p class="text-xs text-base-content/70">Periode <?= htmlspecialchars($movement['start'] ?? '', ENT_QUOTES); ?> sampai <?= htmlspecialchars($movement['end'] ?? '', ENT_QUOTES); ?>. Data berasal dari pesanan selesai.</p></div><span class="text-xs text-base-content/70">Toko: <?= htmlspecialchars($data['movement_shop_name'] ?? 'Toko', ENT_QUOTES); ?></span></div>
    <?php if (!$rows): ?><div class="p-10 text-center"><p class="font-semibold"><?= $activeFilter === "" ? "Belum ada data produk" : "Tidak ada produk di kategori ini"; ?></p><p class="mt-2 text-sm text-base-content/70"><?= $activeFilter === "" ? "Sinkronkan produk dari Daftar produk untuk mulai melihat rekap." : "Pilih kategori lain atau tampilkan semua produk toko ini."; ?></p></div><?php else: ?><div class="overflow-x-auto"><table class="movement-table table w-full" role="table" aria-label="Rekap pergerakan produk"><thead><tr><th>Produk</th><th>Status</th><th class="text-right">Terjual</th><th class="text-right">Rata-rata/hari</th><th class="text-right">Stok</th><th class="text-right">Perkiraan hari</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr role="row"><td role="cell" data-label="Produk"><div class="flex min-w-0 items-center gap-3"><div class="h-10 w-10 shrink-0 overflow-hidden rounded border border-base-300 bg-base-200"><?php if (!empty($row['cover_image'])): ?><img src="https://cf.shopee.co.id/file/<?= htmlspecialchars($row['cover_image'], ENT_QUOTES); ?>" alt="<?= htmlspecialchars('Produk: ' . $row['name'], ENT_QUOTES); ?>" class="h-full w-full object-cover" loading="lazy"><?php endif; ?></div><div class="min-w-0"><strong class="block break-words"><?= htmlspecialchars($row['name'], ENT_QUOTES); ?></strong><span class="text-xs text-base-content/60"><?= htmlspecialchars($row['parent_sku'] ?: 'SKU tidak tersedia', ENT_QUOTES); ?></span></div></div></td><td role="cell" data-label="Status"><span class="badge" data-movement="<?= htmlspecialchars($row['movement_key'], ENT_QUOTES); ?>"><?= htmlspecialchars($row['movement_label'], ENT_QUOTES); ?></span></td><td role="cell" data-label="Terjual" class="text-right"><?= number_format((int)$row['units_sold'], 0, ',', '.'); ?></td><td role="cell" data-label="Rata-rata/hari" class="text-right"><?= number_format((float)$row['daily_rate'], 2, ',', '.'); ?></td><td role="cell" data-label="Stok" class="text-right"><?= number_format((int)$row['total_stock'], 0, ',', '.'); ?></td><td role="cell" data-label="Perkiraan hari" class="text-right"><?= $row['stock_days'] === null ? 'Belum ada laju jual' : number_format((float)$row['stock_days'], 1, ',', '.') . ' hari'; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
  </div>
</section>
